Update requirements.txt: fix transformers version mismatch
fix error traceback start with:
File "xxx\Python310\site-packages\transformers\tokenization_utils_base.py", line 3037, in encode_plus
  padding_strategy, truncation_strategy, max_length, kwargs = self._get_padding_truncation_strategies(
File "xxx\Python310\site-packages\transformers\tokenization_utils_base.py", line 2761, in _get_padding_truncation_strategies
  if padding_strategy != PaddingStrategy.DO_NOT_PAD and (self.pad_token is None or self.pad_token_id < 0):
File "xxx\Python310\site-packages\transformers\tokenization_utils_base.py", line 1104, in __getattr__
  raise AttributeError(f"{self.__class__.__name__} has no attribute {key}")
AttributeError: BertTokenizerFast has no attribute pad_token